const TRENDING={
    LOAD: 'TRENDING_LOAD',
    LOAD_SUCCESS: 'TRENDING_LOAD_SUCCESS',
    LOAD_FAIL: 'TRENDING_LOAD_FAIL',
}

const POPULAR={
    LOAD: 'POPULAR_LOAD',
    LOAD_SUCCESS: 'POPULAR_LOAD_SUCCESS',
    LOAD_FAIL: 'POPULAR_LOAD_FAIL',
}

const SEARCH={
    LOAD:'SEARCH_LOAD',
    LOAD_SUCCESS: 'SEARCH_LOAD_SUCCESS',
    LOAD_FAIL: 'SEARCH_LOAD_FAIL',
}

const SHOWS={
    LOAD:'SHOWS_LOAD',
    LOAD_SUCCESS:'SHOWS_LOAD_SUCCESS',
    LOAD_FAIL:'SHOWS_LOAD_FAIL'
}

export {TRENDING,POPULAR, SEARCH, SHOWS}