const TRENDING={
    LOAD: 'TRENDING_LOAD',
    LOAD_SUCCESS: 'TRENDING_LOAD_SUCCESS',
    LOAD_FAIL: 'TRENDING_LOAD_FAIL',
}

const POPULAR={
    LOAD: 'POPULAR_LOAD',
    LOAD_SUCCESS: 'POPULAR_LOAD_SUCCESS',
    LOAD_FAIL: 'POPULAR_LOAD_FAIL',
}

const SEARCH={
    LOAD:'SEARCH_LOAD',
    LOAD_SUCCESS: 'SEARCH_LOAD_SUCCESS',
    LOAD_FAIL: 'SEARCH_LOAD_FAIL',
}

const SHOWS={
    LOAD:'SHOWS_LOAD',
    LOAD_SUCCESS:'SHOWS_LOAD_SUCCESS',
    LOAD_FAIL:'SHOWS_LOAD_FAIL',
}

const PEOPLE={
    LOAD:'PEOPLE_LOAD',
    LOAD_SUCCESS:'PEOPLE_LOAD_SUCCESS',
    LOAD_FAIL:"PEOPLE_LOAD_FAIL",
}

const MOVIE={
    LOAD:'MOVIE_LOAD',
    LOAD_SUCCESS:'MOVIE_LOAD_SUCCESS',
    LOAD_FAIL:"MOVIE_LOAD_FAIL",
}

const REVIEWS={
    LOAD:'REVIEWS_LOAD',
    LOAD_SUCCESS:'REVIEWS_LOAD_SUCCESS',
    LOAD_FAIL:"REVIEWS_LOAD_FAIL",
}

const RECOMMENDATIONS={
    LOAD:'RECOMMENDATIONS_LOAD',
    LOAD_SUCCESS:'RECOMMENDATIONS_LOAD_SUCCESS',
    LOAD_FAIL:"RECOMMENDATIONS_LOAD_FAIL",
}
const FAVOURITES={
    LOAD:'FAVOURITES_LOAD',
    LOAD_SUCCESS:'FAVOURITES_LOAD_SUCCESS',
    LOAD_FAIL:"FAVOURITES_LOAD_FAIL",
}

export {TRENDING,POPULAR, SEARCH, SHOWS, PEOPLE, MOVIE, REVIEWS, RECOMMENDATIONS, FAVOURITES};